/*
 * generated by Xtext
 */
package org.com.compiladores.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.com.compiladores.ui.internal.CActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CActivator.getInstance().getInjector(CActivator.ORG_COM_COMPILADORES_C);
	}
	
}
