/*
 * generated by Xtext
 */
package org.com.compiladores.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CUiModule extends org.com.compiladores.ui.AbstractCUiModule {
	public CUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
