/*
 * generated by Xtext
 */
package org.com.compiladores.ui.contentassist

import org.com.compiladores.ui.contentassist.AbstractCProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CProposalProvider extends AbstractCProposalProvider {
}
