/*
* generated by Xtext
*/
package org.com.compiladores;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.com.compiladores.ui.internal.CActivator.getInstance().getInjector("org.com.compiladores.C");
	}
	
}
