/*
 * generated by Xtext
 */
package org.com.compiladores;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CRuntimeModule extends org.com.compiladores.AbstractCRuntimeModule {

}
