/*
* generated by Xtext
*/
package org.com.compiladores;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CStandaloneSetup extends CStandaloneSetupGenerated{

	public static void doSetup() {
		new CStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

