/**
 * generated by Xtext
 */
package org.com.compiladores.validation;

import org.com.compiladores.validation.AbstractCValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CValidator extends AbstractCValidator {
}
